name: "LocalDeck Configurator (Dev)"
description: "Configure your LocalBytes LocalDeck with ease!"
slug: "localdeck-configurator-dev"
panel_icon: "mdi:dialpad"

image: ghcr.io/localbytes/hass-localdeck-configurator-{arch}
version: 0.5-31-g46440f6
arch: [ aarch64, amd64, armhf, armv7, i386 ]
init: false

schema:
  esphome_dir: str

options:
  esphome_dir: "/homeassistant/esphome"

map:
  - homeassistant_config:rw

ingress: true
ingress_port: 3000

homeassistant_api: true
